version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: olist_db 
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
    volumes:
      - pg_data:/var/lib/postgresql/data

networks:
  olist_db:

volumes:
  pg_data:
