site_name: My Docs
repo_url: https://github.com/tiago-hs/ppi-airflow
repo_name: tiago-hs/ppi-airflow
edit_uri: tree/main/docs
theme: 
  name: material
  language: pt-BR
  logo: assets/pp_logo.png
markdown_extensions: 
  - attr_list
extra_css:
  - stylesheets/extra.css
