[tool.poetry]
name = "ppi-airflow"
version = "0.1.0"
description = ""
authors = ["Tiago Henrique <tiago.henrique@picpay.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
